name: CI

on:
  push:
    branches:
      - master
      - tiler-dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run the script
        if: matrix.os == 'windows-2022'
        run: |
          ${{ github.workspace }}/setup_tiler_project.bat --ci-workflow

      - name: Run the script
        if: matrix.os != 'windows-2022'
        run: |
          chmod +x ${{ github.workspace }}/setup_tiler_project.sh
          ${{ github.workspace }}/setup_tiler_project.sh --ci-workflow
